# Generated by Django 5.0 on 2023-12-17 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='почтовый адрес')),
                ('initials', models.CharField(max_length=50, verbose_name='инициалы')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='комментарий')),
            ],
            options={
                'verbose_name': 'клиент',
                'verbose_name_plural': 'клиенты',
            },
        ),
        migrations.CreateModel(
            name='MailingSrv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(auto_now_add=True, verbose_name='время начала рассылки')),
                ('finish', models.DateTimeField(verbose_name='время завершения рассылки')),
                ('status', models.CharField(default=('CREATED', 'создана'), max_length=100, verbose_name='статус рассылки')),
                ('frequency', models.CharField(choices=[('DAY', 'раз в день'), ('WEEK', 'раз в неделю'), ('MONTH', 'раз в месяц')], max_length=50, verbose_name='периодичность рассылки')),
                ('recipients', models.ManyToManyField(to='app_mailing.client', verbose_name='получатели рассылки')),
            ],
            options={
                'verbose_name': 'параметр рассылки',
                'verbose_name_plural': 'параметры рассылок',
            },
        ),
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=150, verbose_name='тема письма')),
                ('content', models.TextField(verbose_name='тело письма')),
                ('mailing_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mails', to='app_mailing.mailingsrv', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'письмо',
                'verbose_name_plural': 'письма',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_status', models.CharField(choices=[('success', 'успешно'), ('failure', 'не выполнено')], max_length=50, verbose_name='статус попытки')),
                ('server_response', models.CharField(blank=True, null=True, verbose_name='ответ почтового сервера')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mailing.client', verbose_name='получатель рассылки')),
                ('mailings_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_mailing.mailingsrv', verbose_name='рассылка')),
            ],
            options={
                'verbose_name': 'отчет',
                'verbose_name_plural': 'отчеты',
            },
        ),
    ]
