# Generated by Django 5.0 on 2024-01-06 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mailing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log',
            name='mailings_list',
        ),
        migrations.AddField(
            model_name='log',
            name='mailing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_mailing.mailingsrv', verbose_name='рассылка'),
        ),
        migrations.AlterField(
            model_name='log',
            name='attempt_status',
            field=models.CharField(default='попытка не инициирована', max_length=50, verbose_name='статус попытки'),
        ),
        migrations.AlterField(
            model_name='log',
            name='server_response',
            field=models.TextField(blank=True, null=True, verbose_name='ответ почтового сервера'),
        ),
    ]
