# Generated by Django 5.0 on 2023-12-17 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailingsrv',
            name='status',
            field=models.CharField(default='создана', max_length=100, verbose_name='статус рассылки'),
        ),
    ]
