# Generated by Django 5.0 on 2024-01-07 00:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mailing', '0002_remove_log_mailings_list_log_mailing_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail',
            name='mailing_list',
        ),
        migrations.AddField(
            model_name='mailingsrv',
            name='is_activated',
            field=models.BooleanField(default=True, verbose_name='метка активности'),
        ),
        migrations.AddField(
            model_name='mailingsrv',
            name='mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_mailing.mail', verbose_name='письмо'),
        ),
        migrations.AddField(
            model_name='mailingsrv',
            name='name',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='наименование рассылки'),
        ),
        migrations.AddField(
            model_name='mailingsrv',
            name='next',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время следующей рассылки'),
        ),
        migrations.AlterField(
            model_name='mailingsrv',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='время начала рассылки'),
        ),
    ]
