# Generated by Django 4.2.7 on 2024-01-19 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_mailing', '0002_client_owner_mail_owner_mailingsrv_owner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailingsrv',
            options={'ordering': ('pk',), 'permissions': [('set_is_activated', 'переключатель метки активности')], 'verbose_name': 'параметр рассылки', 'verbose_name_plural': 'параметры рассылок'},
        ),
    ]
