# Generated by Django 5.0 on 2024-01-07 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mailing', '0003_remove_mail_mailing_list_mailingsrv_is_activated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='attempt_status',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='mailingsrv',
            name='frequency',
            field=models.CharField(choices=[('единоразово', 'единоразово'), ('раз в день', 'раз в день'), ('раз в неделю', 'раз в неделю'), ('раз в месяц', 'раз в месяц')], max_length=50, verbose_name='периодичность рассылки'),
        ),
    ]
